version: '3.8'
services:
  backend:
    container_name: $MS_NAME
    image: $MS_NAME:$BUILD_ID
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - $HOST_PORT:$DJANGO_PORT
    volumes:
      - .:/app